### ISSUE TITLE
API documentation?

### ISSUE THREAD

**Issue by winnall** [Olen/Spond#1]
Is there any further documentation on the API you use to access Spond data? I want to link Spond to our website and the two need to exchange data.

**Comment by Olen** [comment]
This is 100% reverse engineered from the Spond webpage, so the documentation is pretty scarce.
The api is not "official" in the sense that Spond does not publish any information about it.

**Comment by winnall** [comment]
Thanks. Is this what they use for their mobile apps?

**Comment by Olen** [comment]
I don't know, but I guess so. It is what they use for their web app. I doubt they have different apis for web and mobile, but I have not reverse engineered the mobile app.
