### ISSUE TITLE
What does `getEvents()` actually return, and is there a way to get more past events?

### ISSUE THREAD

**Issue by elliot-100** [Olen/Spond#10]
Readme says 'Gets all upcoming events', implying future events.

But running it right now for a club with events from early 2021, I seem to get all events from 2022-04-23 (a few weeks ago) to present, as well as all those in the future.

(Not a code issue, but I'm fairly sure the web and mobile Spond clients (including 'download attendance as XLSX') only include the last calendar year's events or so, so it may be not be possible to get all past events)

**Comment by elliot-100** [comment]
Now I've actually checked the code 😉 I can see that `getEvents()` default behaviour is to return events from today - 14 days.

And it's possible to pass a parameter to go further back e.g.

```
...
end_time = datetime.now() - timedelta(days=365)
events = await spond_session.getEvents(end_time)
...

It does look like there's a limit of 100 events returned though.

**Comment by elliot-100** [comment]
Pull request to amend README: #11

**Comment by Olen** [comment]
Merged PR.  Thanks
