### ISSUE TITLE
Collect previous attendance data

### ISSUE THREAD

**Issue by hansand02** [Olen/Spond#100]
Is there any way to collect the attendance data for the previous year or so? 

Right now i can only get data going back to the 19th of February ( today is the 25th ), by using these parameters in the given attendance script:

```    
max_end = datetime(2024, 3, 1)
events = await s.get_events(max_end=max_end)
```

**Comment by elliot-100** [comment]
How many events are returned? Defaults to a max of 100.

**Comment by elliot-100** [comment]
If I run this very simplified version of `attendance.py` with your `max_end` against one of my groups:

```
import asyncio
from datetime import datetime

from config import password, username
from spond import spond


async def main():
    s = spond.Spond(username=username, password=password)
    max_end = datetime(2024, 3, 1)
    events = await s.get_events(max_end=max_end, max_events=1000)

    print(f"{len(events)} events")
    for e in events:
        print(f"{e['startTimestamp']}")
    await s.clientsession.close()

loop = asyncio.new_event_loop()
asyncio.set_event_loop(loop)
asyncio.run(main())
```

I get 100s of event timestamps from:

`2024-02-29T18:15:00Z`
to 
`2021-04-25T08:00:00Z`

Do you get any error messages?

**Comment by hansand02** [comment]
I see. I tried the code you provided now and it gave 6 events, leading back up until the date of me joining the current club. 

I guess that means im not authorised to gather data further back than the creation of my profile!

Thanks for helping:)

**Comment by elliot-100** [comment]
The code uses the same API as web/app clients, so you should expect to be able to get the same set of events as you can see in those. There are quite a few factors in whether a given event is visible to a given user.
