### ISSUE TITLE
Discussion: what exception to raise for a failed lookup by id?

### ISSUE THREAD

**Issue by elliot-100** [Olen/Spond#113]
Currently `get_event(id)` and `get_group(id)` raise built-in `IndexError`  if `id` is not matched. NB `IndexError` subclasses base class `LookupError`.

Although I originally implemented this, I don't think it's correct, as ([paraphasing docs](https://docs.python.org/3/library/exceptions.html#IndexError)) this is intended where an integer subscript is out of range; and `id` is `str` not `int`.

@ptmminh suggested `ValueError` ([docs](https://docs.python.org/3/library/exceptions.html#ValueError)) but this should be:

> raised when an operation or function receives an argument that has the right type but an inappropriate value, and the situation is not described by a more precise exception such as [IndexError](https://docs.python.org/3/library/exceptions.html#IndexError).

I think we should be more precise, and so it should be one of:

- built-in `KeyError` ([docs](https://docs.python.org/3/library/exceptions.html#KeyError)) which subclasses base class `LookupError` - as `id` is a key to a mapping (dict), even though it happens to be inside a list
- custom exception e.g. `IDMatchError` which subclasses base class `LookupError`

Let me know what you think.

**Comment by dhomeier** [comment]
Would have considered `ValueError` as well, but as the docs state a more precise exception type should be preferred, I'd agree with •1 that `KeyError` would be that more precise type, and also what I'd generally expect in such a case.

**Comment by ptmminh** [comment]
sorry @elliot-100 I missed this note earlier! Agree that `KeyError` is probably best!
