### ISSUE TITLE
Release 1.0.0! [was: New release please!]

### ISSUE THREAD

**Issue by elliot-100** [Olen/Spond#133]
Hi @Olen, could you publish a new PyPI/Github version please?

I guess it would be numbered 1.0.0?

I'm currently using this interim release on my own fork:
https://github.com/elliot-100/Spond/releases/tag/0.99.1%2Bbuild1

I think looking at the auto-generated notes they could be significantly simplified, and there may be one or two user attributions missing due to the way I merged a couple of things.

If OK, I am happy to draft a release here if useful?

**Comment by Olen** [comment]
Version 1.0.0 released and pushed to pypi

**Comment by Olen** [comment]
Sorry. just pushed the release inbetween $dayjob here

**Comment by Olen** [comment]
And a HUGE thanks to both you @elliot-100 and the rest of you guys.
I have not had much time lately to focus on this, so I am very happy that you keep pushing.
