### ISSUE TITLE
Please could you add tag for current release 0.0.5?

### ISSUE THREAD

**Issue by elliot-100** [Olen/Spond#15]
..and for each future release? This would really help contributions.

I think it's this commit: https://github.com/Olen/Spond/commit/68677d605102a715d21f7ce6989a082cf80f718c

Cheers, Elliot

**Comment by Olen** [comment]
I was not able to create a release so many commits back  Created a 0.0.6-release instead.
Have not pushed it to gitlab yet

**Comment by elliot-100** [comment]
Thanks!  I see it now on GitHub.

Note though that you can tag any revision, as it's a Git repo feature -- as opposed to Release which is an additional GitHub feature on top.
