### ISSUE TITLE
Propose marking members as non-public and moving public `AuthenticationError`

### ISSUE THREAD

**Issue by elliot-100** [Olen/Spond#162]
I think these members shouldn't be used by end-users and therefore should be prefixed with `_`:

```
spond.spond.Spond.chat_url
spond.spond.Spond.auth
spond.spond.Spond.login_chat()
```
I think this one should be moved:
```
spond.base.AuthenticationError -> spond.AuthenticationError
```
as `spond.base` should only contain the internal `_SpondBase`class.

I am not sure if this should be considered a breaking change.

But once we have done this, I think we probably have the correct public API, and so will make it clearer in future:

- what should be properly documented 
- what is a breaking change/functional addition/removal (as it affects part of the public API)
- what can be freely refactored/removed (as it only affects internals).

**Comment by Olen** [comment]
I think it is pretty obvious that those functions are not meant to be public, so if anyone have used them in 3. party code, they should not be surprised if they change.
So to me it sounds reasonable to prefix them with _ and don't worry about breaking anything.
