### ISSUE TITLE
Still being developed?

### ISSUE THREAD

**Issue by elliot-100** [Olen/Spond#20]
Hi, just wondering if any further development is likely?

I'm thinking of releasing my fork as a new, separate package, as I increasingly need to introduce incompatible changes.

**Comment by Olen** [comment]
Hi,

Sorry for my late responses, but it's been summer, and I have had other priorities.  I don't think two seperate packages is a viable way forward, but I'll add you as a collaborator so you can be moe involved directly.

Just out of curiosity, what kind of incompatible changes are you working on, and why?
And how are you using the package?  Just looking for good ideas here.

**Comment by elliot-100** [comment]
Hi, no worries, have other priorities too!

Agree a single package is preferable,
Thanks for adding me as collaborator.
I will rethink my changes and put them as proposal 'issues' for discussion.

So far I am using the package to streamline a few aspects of managing a cycling club, e.g.:

- Identify likely club member permission issues, by comparing roles and group/subgroup membership
- Report monthly prospective member volumes (we have a seperate group for this) by analysing subgroup membership, factoring in event attendance
- Other reporting, e.g. events per month

**Comment by elliot-100** [comment]
Think this question is answered ;)
