### ISSUE TITLE
get Spond data

### ISSUE THREAD

**Issue by Allmoi0815** [Olen/Spond#21]
Thank you for this code. I'm a PHP-developper, so I have to translate it. I work with "cUrl".
Now, I just finished the first step (login), so I get back a token and my phonenumber. Additionally I get a message on my mobile with a code.
But I don't know how to resend this, to get the data (e.g. getEvents).
Can someone help me?
Thank you in advance.

**Comment by Olen** [comment]
Sounds like 2 factor authentication.  Since the message is sent to your phone, it is extremely hard to automate any login with 2FA enabled.  
So either you need to turn off 2FA in Spond, or you must find a way to manually enter the code every time.

**Comment by Allmoi0815** [comment]
Since I've disabled the 2fa, no data is in the response (only "{}"). 
When using a wrong name/passwort, I'll receive a message ("wrongEmailOrPassword"). So I think, my code is right.
Any other hints?

**Comment by Allmoi0815** [comment]
Thanks a lot for your help. Now it works for me with PHP.
Do you know if there are other methods to work with?

**Comment by elliot-100** [comment]
What are you trying to do?

**Comment by Allmoi0815** [comment]
I wan't to get the events of all subgroups, but this is only possible, if the user is part of the group. Do you know if there is another way to do that?
Another idea is to send posts over the api. Is this possible?
I want to send messages to a group (type="GROUP", name="test"). How do I put this into the "recipient"?

**Comment by elliot-100** [comment]
> get the events of all subgroups, but this is only possible, if the user is part of the group

As far as I know the user has to be a member of a group to get info about it.

> send messages to a group

I have never used this functionality, but I guess you could get all the members of a group, then send to each one individually. I believe migrating to the 'Spond Clubs' functionality gives more messaging options in the UI.

Remember that the API is undocumented, so functions provided in the code here are the result of experimenting, and examining the resulting API calls made from the browser.

**Comment by elliot-100** [comment]
Closing as it appears to have been answered as far as possible (and it's really about Spond API in general, not within scope of this project)
