### ISSUE TITLE
Use PEP-8 naming conventions

### ISSUE THREAD

**Issue by elliot-100** [Olen/Spond#24]
I would really like to use need to use standard-pattern function names for compatibility with other code.

This pull request converts function names in the the API and docs.
It doesn't address e.g. variable names in sample code.

#23

**Comment by Olen** [comment]
I'll look at it, and I like the idea, so I'll probably merge it as soon as I have some time to rewrite my own scripts.

Thanks a lot for the effort

**Comment by Olen** [comment]
Let's see what I can do thie evening or tomorrow.  There is a school holiday this week, so no football or other activities with the kid that I have to participate in in the evenings.

**Comment by elliot-100** [comment]
Thanks!
