### ISSUE TITLE
Add extra parameters to  `get_events()` method

### ISSUE THREAD

**Issue by elliot-100** [Olen/Spond#25]
At the moment there isn't a general-purpose method to get events.

e.g. `getEvents` can only get up to 100 events, and defaults to last 14 days; `getEventsBetween` can get more but requires date parameters. There is no way of restricting events to a Group.

I propose that `get_events` (PEP 8 naming as per #24) is expanded to:
- Default to a max, probably 100 for performance reasons, as `getEventsBetween` does now.
- Optional before/after datetime parameters, as `getEventsBetween` requires now (although I think the names could better reflect what they do)
- Optional Group ID filter parameter, as per #14 
- Other optional parameters can then be added over time.

It might make sense to then have some supplementary 'shortcut' methods, but `get_events_between` may be redundant; I think it's too early to worry about backward compatibility.

I'm writing a PR for this, but any thoughts?

**Comment by Olen** [comment]
I totally agree.
It makes more sense to have a "generic" `get_events` with optional parameters, than different functions to basically do the same thing.

**Comment by elliot-100** [comment]
Thank you!
