### ISSUE TITLE
Spond Robots.txt

### ISSUE THREAD

**Issue by morkohl** [Olen/Spond#40]
Hey I didn't know this but have you gus looked at the robots.txt from spond.com?

```
# Notice: Crawling Spond.com is prohibited unless you have written permission.

User-agent: *
Disallow: /landing
Disallow: /images/
Disallow: /storage/
Disallow: /api/
Disallow: /client

```

Since you're explicitly calling `http://spond.com/api/2.1` maybe it would be worth a reminder in your README.

**Comment by Olen** [comment]
I am pretty sure this does not count as "crawling".

> A robots.txt file tells search engine crawlers which URLs the crawler can access on your site. This is used mainly to avoid overloading your site with requests

We are just using the API the same way as the website and app.
