### ISSUE TITLE
In git tag 0.90 / GitHub release 0.9.0, setup.cfg says version is still 0.0.6

### ISSUE THREAD

**Issue by elliot-100** [Olen/Spond#41]
This issue does not appear in PyPI release 0.9.0, however.

This is likely to cause issues if installing from GitHub instead of PyPI.

**Comment by Olen** [comment]
Thanks.

Updated setup.cfg now

I don't really have a nice and working release flow for this project (yet).

**Comment by elliot-100** [comment]
Thanks.

Will leave this open for now, as I don't think the issue will actually be resolved until a git tag > 0.9.0 exists, as e.g. `pip install git+https://github.com/Olen/Spond.git@v0.9.0#egg=Spond` targets a tag. 

Have you thought of using Poetry? I have just switched to it for personal projects which depend on Spond, and it handles e.g. dependency versioning  well (which is something else that could do with tidying here). I understand it also does publishing to PyPI but have not used that yet.

**Comment by Olen** [comment]
Yeah.  I have several projects that I would like to get more control over.
They all started as tiny, personal projects, and suddenly people are actually using them...

I'll look into poetry. Don't hesitate to give me some hints on how an where to start.
