### ISSUE TITLE
getMessages() doesn't work

### ISSUE THREAD

**Issue by elliot-100** [Olen/Spond#5]
`https://spond.com/api/2.1/chats/?max=10` returns a 404 error, so presume messages are no longer available via the API...

**Comment by Olen** [comment]
Hm.
Now I am getting a dfferent 404 (I actally got a directory listing directly on Spond.com a minute ago).
I know it used to work, but the API undocumented, so they might have changed something.  Let's have a look....

**Comment by Olen** [comment]
Hey have changed to URL to (the more correct, I guess) chat.spond..com
And it requies an extra header

**Comment by elliot-100** [comment]
Great - thanks! 👍
