### ISSUE TITLE
`ical.py` example script fails

### ISSUE THREAD

**Issue by elliot-100** [Olen/Spond#51]
```
...
File "C:\Users\Elliot\dev\Olen-Spond\ical.py", line 34, in main
    event["location"]["feature"], event["location"]["address"]
KeyError: 'address'
...
```
Presume a Spond event doesn't have any `address`.
Realise this script is only intended as an example implementation.

(Issues like this could be spotted more easily during dev by assuming most (all)? attributes are optional, adding type hints to Spond codebase accordingly, then using `mypy` or similar,...)

**Comment by Olen** [comment]
Works here, but I guess I have addresses for all locations. But I'll create a PR that adds `.get()` around these for the example.

**Comment by Olen** [comment]
Fixed
