### ISSUE TITLE
Character encoding issue in `ical.py` on Windows

### ISSUE THREAD

**Issue by elliot-100** [Olen/Spond#53]
After applying fix #52 for issue #51:
```
C:\Users\Elliot\AppData\Local\pypoetry\Cache\virtualenvs\spond-4LxEsJ8S-py3.7\Scripts\python.exe C:\Users\Elliot\dev\Olen-Spond\ical.py
Traceback (most recent call last):
  File "C:\Users\Elliot\dev\Olen-Spond\ical.py", line 44, in <module>
    asyncio.run(main())
  File "C:\Users\Elliot\AppData\Local\Programs\Python\Python37\lib\asyncio\runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "C:\Users\Elliot\AppData\Local\Programs\Python\Python37\lib\asyncio\base_events.py", line 587, in run_until_complete
    return future.result()
  File "C:\Users\Elliot\dev\Olen-Spond\ical.py", line 38, in main
    out_file.writelines(c)
  File "C:\Users\Elliot\AppData\Local\Programs\Python\Python37\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode characters in position 8-11: character maps to <undefined>
```
Assume one or more fields in my personal Spond data contain non-ASCII characters; similar issues likely in other scripts.
It would be good to set up a standard dataset for testing this and similar issues.

**Comment by Olen** [comment]
Fixed

**Comment by Olen** [comment]
I think it handles unicode (utf8) in calendars - i definitely have non-ascii characters in many of my events), but if yu run this on windows, you might be using some other charset locally which might cause issues?

**Comment by elliot-100** [comment]
Ah a bit of searching says you are right! Looks like it's trying to encode a glyph that isn't in the Windows 1252 character set. I need to isolate but suspect it's an emoji...

**Comment by elliot-100** [comment]
I'm going to close this at it's frankly too obscure to worry about. It might ultimately be better to put a disclaimer about Windows in the README, I'll keep the somewhat similar #36 open as it can be simply fixed when I get round to it.
