### ISSUE TITLE
Getting group members

### ISSUE THREAD

**Issue by TimCoates** [Olen/Spond#58]
Hi could you give an example of getting all members of a group please. Ideally (stretch goal) of adding and removing members?

**Comment by elliot-100** [comment]
Hi - have you tried the sample code in README.md? That gets all your groups, and prints the name of each. If you replace `group['name']` with `group['members']` you'll see the members dict.

If you run example code `groups.py` you can see the info structure of the groups dict.

**Comment by TimCoates** [comment]
Thanks
