### ISSUE TITLE
`spond-classes`: separate class abstraction layer

### ISSUE THREAD

**Issue by elliot-100** [Olen/Spond#63]
I've got to the stage with my class abstraction layer that I want to promote it a bit - hope that's OK.

It provides read-only acesss to Group, Member, Subgroup, Role, Event instances.

For the time being, it's a separate package depending on this one and is very partial - only covers what I need for my current read-only use cases.

https://github.com/elliot-100/Spond-classes

Pull requests to add attributes etc, discussions, issues are welcome there.

**Comment by Olen** [comment]
Looks great.
If you don't mind, I am more than happy to have something like this merged and released as a version 1.0

**Comment by elliot-100** [comment]
Yes I would like that to happen eventually. Would need a lot of work though to add write methods etc...

**Comment by elliot-100** [comment]
Closing - already covered by #57
