### ISSUE TITLE
Publish as package?

### ISSUE THREAD

**Issue by elliot-100** [Olen/Spond#7]
Hi - am at the point of using this code in one of my projects, and was wondering if you would be willing to publish as an installable, versioned package - here on Github, if not on PyPI - in order to make deployment easier.

I have attempted to do this myself on my fork, but have only packaged very simple modules previously and am struggling with specifiying dependencies.

Many thanks,

**Comment by Olen** [comment]
Thanks for the nudge

This is now installable with pip:

https://pypi.org/project/spond/

**Comment by elliot-100** [comment]
Fantastic - really appreciated!

Elliot
