### ISSUE TITLE
Has anyone tried using this with the Spond Club system?

### ISSUE THREAD

**Issue by elliot-100** [Olen/Spond#70]
Spond Club overview: https://www.spond.com/spond-club-overview/

I've only used it with groups in the older/simpler Spond App/Team system.

Groups need to be migrated from there to Spond Club (https://help.spond.com/en/articles/25770-spond-club-setup-guide-for-clubs-with-existing-groups-in-the-spond-app) so I guess it's a different schema with different, incompatible API access?

**Comment by ptmminh** [comment]
Our club only started using Spond late 2023 so I'll have to check out the links above to see what the migration is about. 

However, afaict, it does seem like Spond Club accesses an entirely different API endpoint with different schema altogether. 

e.g. group ID i can see in the web client (spond.com/client) is different than the group ID passed into the club API endpoint.

**Comment by elliot-100** [comment]
Closing, as it's been answered.
